### ISSUE TITLE
Provide extendable docker image

### ISSUE THREAD

**Issue by saulshanabrook** [progrium/buildstep#131]
I would love if it would be possible to turn this project into one docker image that could be used as a base image. It would be great to be able to do something like this:

```bash
$ cat Dockerfile
FROM progrium/buildstep
CMD /start web
$ docker build -t myapp .
...output...
$ docker run myapp
...running...
```

This would be great for me, because it would allow me to use my app just like any other Docker app, without having to worry about installing anything on my computer and compiling tarballs. 

It looks like [tutumcloud/buildstep](https://github.com/tutumcloud/buildstep) does basically this, but I am wondering if there is a reason not to include htis behavior in this repo.

**Comment by progrium** [comment]
Um. You can already do this if you want.

On Saturday, January 17, 2015, Saul Shanabrook <notifications@github.com>
wrote:

> I would love if it would be possible to turn this project into one docker
> image that could be used as a base image. It would be great to be able to
> do something like this:
>
> $ cat Dockerfile
> FROM progrium/buildstep
> CMD /start web
> $ docker build -t myapp .
> ...output...
> $ docker run myapp
> ...running...
>
> This would be great for me, because it would allow me to use my app just
> like any other Docker app, without having to worry about installing
> anything on my computer and compiling tarballs.
>
> It looks like tutumcloud/buildstep
> <https://github.com/tutumcloud/buildstep> does basically this, but I am
> wondering if there is a reason not to include htis behavior in this repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/buildstep/issues/131>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by saulshanabrook** [comment]
Haha OK. Do you think it would make sense to include this on the readme?

**Comment by progrium** [comment]
Yes, but the project is about to go through some major changes to where it actually won't make sense here. I'll make a note of it in appropriate docs though.

**Comment by yngndrw** [comment]
I might be missing something, but I can't find any mention of just using a Dockerfile for an application rather than a build pack in the documentation.

What are the upcoming changes which affect this ? I would like to be able to run some applications with a totally different Docker container. (Specifically: https://github.com/aspnet/aspnet-docker)
