### ISSUE TITLE
Update Ruby Buildpack

### ISSUE THREAD

**Issue by dyson** [progrium/buildstep#132]
The ruby buildpack (don't know if it is an issue in other buildpacks as I only use the ruby one) needs to be updated as https://github.com/heroku/heroku-buildpack-ruby/issues/335 resolved time outs with the nodejs.org servers during deploy.

Without this update deployment for me is impossible.

**Comment by progrium** [comment]
Can you just update the https://github.com/progrium/buildstep/blob/master/builder/config/buildpacks.txt file with the right revision/tag as a PR?

**Comment by dyson** [comment]
Sure thing.

v130 fixed it but v133 is the latest which I am using and everything is working great.
