### ISSUE TITLE
run tests in docker container

### ISSUE THREAD

**Issue by progrium** [progrium/buildstep#134]
@yabawock it would be really rad if you could consolidate everything related to running tests under `tests` directory that had it's own Dockerfile to run the tests in Docker, given a mounted Docker socket file. I'm having trouble running the tests consistently in different environments. :)

**Comment by yabawock** [comment]
Ok, i'll have a look at it. Just to he clear, you're Loopings for a Dockerfile that runs the current test suite in a container which spins up the different test applications in additional containers on the host.

**Comment by progrium** [comment]
yep!

**Comment by yabawock** [comment]
@progrium Code is in PR #140, should be good to merge. The test suite is currently running on wercker, but the test run for my branch is available here: https://app.wercker.com/#build/54e21ac377795a6f6104b684
