### ISSUE TITLE
NioGroovyMethods not loaded in grails app

### ISSUE THREAD

**Issue by kastork** [progrium/buildstep#142]
I have a grails 2.4.4 app that I'm trying to containerize in buildstep, I get the following warning

```
Extracting /app/.grails/wrapper/grails-2.4.4-download.zip to /app/.grails/wrapper/2.4.4
Mar 9, 2015 10:30:47 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
```
Then again later in the build

```
Executing ./grailsw -plain-output -Divy.default.ivy.user.dir=/cache war --non-interactive
Mar 9, 2015 10:33:12 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
```

And then, when the production war is being packaged

```
|Packaging Grails application
       .........................................................Error
       |
       Error loading plugin manager: Could not create a new instance of class [org.codehaus.groovy.grails.plugins.web.mapping.UrlMappingsGrailsPlugin]! (Use --stacktrace to see the full trace)
       !     Failed to build app
```

Most references to this problem I can find on the internet indicate that this usually pops up when the java version is < 1.7.  There are also some indications that OpenJDK might be part of the problem.

What would be required to get the buildstep container to install an Oracle java version of my own choosing?

**Comment by yabawock** [comment]
I don't think the heroku buildstep supports Oracle Java as you need to accept a license agreement before even downloading it. You can configure the Java version being used by Buildstep in a `system.properties` file, see https://devcenter.heroku.com/articles/java-support#supported-java-versions for more details. 

Buildstep should give you an indiction as to which JDK version is being used/installed at the beginning of the process, something along the lines of

```
-----> Java app detected
-----> Installing OpenJDK 1.7... done
```

**Comment by kastork** [comment]
I've gotten openjdk 8 to work.  There are other docker images that have oracle Java, though... Would be a nice option.
