### ISSUE TITLE
Pass env variables to the compile step

### ISSUE THREAD

**Issue by jakubholynet** [progrium/buildstep#81]
I have a problem with the Clojure buildpack due to buildstep not passing it the path to a dir with env variables. I suppose it is also a problem for other buildpacks. The problem is that the buildpack makes env vars set via `config:set` visible only at runtime, not at compile time - unless they are whitelisted for being used also at compile time by [enumerating them in the env var `BUILD_CONFIG_WHITELIST`](https://github.com/heroku/heroku-buildpack-clojure#configuration). *However setting this has no effect unless `compile` is invoked with a third param, namely a directory with the env variables - which is not done*.

I suppose that the ENV_DIR should be passed on to the buildpack (unless this is some dokku - heroku mismatch).

The relevant code is:
https://github.com/progrium/buildstep/blob/master/stack/builder#L54:

    $selected_buildpack/bin/compile "$build_root" "$cache_root"

and https://github.com/heroku/heroku-buildpack-clojure/blob/master/bin/compile:

    10 export ENV_DIR=$3
    ...
    115 # extract environment
    116 if [ -d "$ENV_DIR" ]; then
    117     # if BUILD_CONFIG_WHITELIST is set, read it to know which configs to export
    118     if [ -r $ENV_DIR/BUILD_CONFIG_WHITELIST ]; then
    119         for e in $(cat $ENV_DIR/BUILD_CONFIG_WHITELIST); do
    120             export "$e=$(cat $ENV_DIR/$e)"
    121         done

Or am I missing something? Thank you!

**Comment by progrium** [comment]
ENV_DIR for buildpacks is supported in the herokuish branch here. Can you try against that version?

**Comment by jakubholynet** [comment]
Nice. It is not easy for me anymore to try this out since I am away from the project where I experienced the problem  but I will try to find the time to try to replicate it.

**Comment by progrium** [comment]
Thank you :)

**Comment by yabawock** [comment]
BTW, the ENV_DIR is also supported in the current buildstep image, no idea if dokku etc. are using it though..

**Comment by vincentfretin** [comment]
@yabawock Yes, Dokku supports ENV_DIR since https://github.com/progrium/dokku/commit/7d5e0ba5aaa454bed5c0766d13f5d5bdaf054bf1
