### ISSUE TITLE
security?

### ISSUE THREAD

**Issue by rvalyi** [progrium/buildstep#88]
Hello,

If I'm not mistaken inside a user container you are the "developer" user but you can do "sudo".
Isn't there a risk that a development environment could be crafted so that the container could attack the host somewhat?

I see that other Docker stack advise to use a USER statement in the Dockerfile to avoid that 
https://github.com/deis/deis/issues/26

Sorry, I'm not a Docker specialist, I could be wrong, but what do you think?

**Comment by mc0e** [comment]
I think security and permissions need more thinking through.  Application source code should generally not be writeable by the web user.  I think we need a user which gets ownership of most of the files from the compile process, and a separate user which runs the app, with a few areas set up to be writeable by the runtime user as required.  Volume mounts for things like file uploads will generally want to be writeable at runtime, but also there may be things like cache directories which are writeable but ephemeral.
